FROM base
ARG NERF_ACC_VER=0.5.2

RUN cd /tmp &&\
    wget https://github.com/KAIR-BAIR/nerfacc/archive/refs/tags/v${NERF_ACC_VER}.tar.gz &&\
    tar xvzf v${NERF_ACC_VER}.tar.gz &&\
    cd nerfacc-${NERF_ACC_VER} &&\
    python setup.py install &&\
    rm -rf /tmp/*

RUN pip install nerfstudio --no-deps

CMD ns-install-cli --mode install && /bin/bash