# run: conda env create -f environment.yml
name: plenoxel
channels:
  - defaults
dependencies:
  - pip:
      - imageio
      - imageio-ffmpeg
      - ipdb
      - lpips
      - opencv-python>=4.4.0
      - Pillow>=7.2.0
      - pyyaml>=5.3.1
      - imageio
      - imageio-ffmpeg
      - pymcubes
      - moviepy
      - matplotlib
      - scipy>=1.6.0

